---
- name: install libselinux-python
  yum: name=libselinux-python state=latest

- name: common packages
  yum: name={{item}} state=installed
  with_items:
    - htop
    - wget
    - vim
    - git
    - tree
    - git


- seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes