ansistrano_deploy_to: "/var/www"
ansistrano_deploy_via: "git"
#ansistrano_version_dir: "releases"
ansistrano_current_dir: "html"
#ansistrano_current_via: "symlink"
ansistrano_keep_releases: 3

# Variables used in the Git deployment strategy
ansistrano_git_repo: https://github.com/mariosanchez/mpwar_performance_exercise.git
ansistrano_git_branch: master

## Variables used in the S3 deployment strategy
#ansistrano_s3_bucket: s3bucket
#ansistrano_s3_object: s3object.tgz # Add the _unarchive suffix to the ansistrano_deploy_via if your object is a package (ie: s3_unarchive)
#ansistrano_s3_region: eu-west-1
#ansistrano_s3_rgw: false # must be Ansible >= 2.2. use Ceph RGW (when set true, ignore ansistrano_s3_region)
#ansistrano_s3_url: http://rgw.example.com # when use Ceph RGW, set url
## Optional variables, omitted by default
#ansistrano_s3_aws_access_key: YOUR_AWS_ACCESS_KEY
#ansistrano_s3_aws_secret_key: YOUR_AWS_SECRET_KEY

ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/deploy/after-cleanup.yml"